language: node_js

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  - pip install --user restructuredtext_lint
  - pip install --user flake8
  - flake8 --exclude closure -v .
  - rst-lint plugin/omero_viewerng/README.rst

#script:
#  - npm run prod
# - python plugin/setup.py sdist install --user || exit 1